export const productsCads = [
  {
    index: "1",
    type: "sneackers",
    img: "https://cdn.etrias.nl/media/cache/product_thumb_md/f/u/fusion-20-bright-whitefoggy-dewphp8dufhc.png",
    desc: "Karhu Fusion 2.0 Bright White / Foggy Dew",
    price: 150
  },

  {
    index: "2",
    type: "sneackers",
    img: "https://cdn.etrias.nl/media/cache/product_thumb_md/w/a/wave-rider-beta-nimbus-cloud-quiet-shade-harbor-mistphpambnqz.png",
    desc: "Karhu Fusion 2.0 Bright White / Foggy Dew",
    price: 180,
  },
  {
    index: "3",
    type: "sneackers",
    img: "https://cdn.etrias.nl/media/cache/product_thumb_md/w/o/womens-campo-chrome-free-leather-extra-white-greyphpitf99m_1.png",
    desc: "Karhu Fusion 2.0 Bright White / Foggy Dew",
    price: 150 ,
  },
  {
    index: "4",
    type: "sneackers",
    img: "https://cdn.etrias.nl/media/cache/product_thumb_md/c/p/cpm051215-studiofoto1_1.png",
    desc: "Karhu Fusion 2.0 Bright White / Foggy Dew",
    price: 150,
  },
  // {
  //   index: "5",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
  // {
  //   index: "1",
  //   type: "sneackers",
  //   img: "",
  //   desc: "",
  //   price: "",
  // },
];
